In [1]:
import numpy as np

In [2]:
list=[1,2,3,4]

In [3]:
np.array(list)

array([1, 2, 3, 4])

In [6]:
matr=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(matr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(1,13,2)

array([ 1,  3,  5,  7,  9, 11])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.array(list)

array([1, 2, 3, 4])

In [23]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [38]:
r=np.random.randint(0,50,10)

In [39]:
r

array([45, 46, 45, 29, 19,  3, 45, 13, 37, 24])

In [40]:
r.max()

46

In [41]:
r.argmax()

1

In [42]:
r.min()

3

In [43]:
r.argmin()

5

In [44]:
r.sort()

In [45]:
r

array([ 3, 13, 19, 24, 29, 37, 45, 45, 45, 46])

In [46]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [60]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [61]:
np.array(la)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [52]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])